### ISSUE TITLE
Feature: Improve CLI interface to targets 

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#1]
## 1. In the current CLI there is unnecessary `-t <target>`
It should be:
`tea <target>`

Call without target should print tea version, usage help, (possibly available targets).

## 2. Passing arguments to the called top-level targets should be possible:

Example target:
```yaml
targets:
  build:
    args:
    - tag
    script: |
      docker build -t ${tag} .
```

In this example passing the `tag` variable should be as easy as possible:

- option 1:
`tea build -a tag=latest`
- option 2:
`tea build -tag latest`
