### ISSUE TITLE
Feature: Override dependency

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#11]
- Add possibility to inject value in place of dependency output

```
release:
  deps:
   - build: {override version: latest}

build:
  deps:
    - version
   script: |
     docker build -t img:${version}  #- > latest      

version:
  script: |
    git rev-parse HEAD     # -> does not execute due to the override
```
