### ISSUE TITLE
Add multi yaml file loading 

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#13]
Possiblity to organize scripts based to multiple files and load them
```yaml
loads:
  - name: docker 
     path: "./sub-file-docker-cmds.yaml"

targets:
  build:
    - docker.build: {tag: myimg}
```
