### ISSUE TITLE
Aliasing dependecies for shell variable names

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#14]
To avoid name collision between args, globals and dependencies, aliasing a dependency name should be possible.

```
build:
  deps:
  - git-tag: {}
     alias: version  #
  script: |
    docker build -t foo:${version}
```
