### ISSUE TITLE
Feture: HTTP get yaml when loading

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#15]
Depends on: #13 
```
loads:
  - name: common-scripts
     path: "http://github.com/common.yaml"
    checksum: "abcd1234" 
```
