### ISSUE TITLE
Set variable inside script

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#18]
Returning variable to script, not only stdout
This would allow to use the stdout freely, without constant /dev/null, and set the variable name using IPC.

```
build:
  deps:
  - version: {}
     opts: returns
  script: |
    echo ${build}        # ->>  1.0

build:
  script: |
    echo "Getting the version..."
    tea return "1.0"       # ->> ipc to parent process
```

This is a bit of a stretch, and would absolutely break in docker or ssh.
Using files to communicate would be just as easy workaround, though a first-class way to do so would be better.
