### ISSUE TITLE
Feature: Handle system environment variables

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#2]
## 1. By default all system environment variables (variables in the environment during the call of the `tea` binary) should be exposed to the target script.

eg.:
```
targets:
  hello:
    script: |
      echo hello ${SOME_VAR}
```
`SOME_VAR=world tea hello`
result: `hello world`

## 2. Global variable should overwrite environment variables (as in make)

eg.:
```
globals:
  some-var: "foo"

targets:
  hello:
    script: |
      echo ${SOME_VAR}
```
`SOME_VAR=world tea hello`
result: `hello foo`

**Unless**:  `?:` "operator" is used in global the assignment.
eg.:
```
globals:
  some-var?: "foo"

targets:
  hello:
    script: |
      echo ${SOME_VAR}
```
`SOME_VAR=world tea hello`
result: `hello world`

## 3. Local variables (args) always takes precedence.

If a local variable is defined, with the same name as a sys env var, the local var should be used in the script.

(Out of scope) reference to global variables should be possible

## 4. Add Setting to shield target script environment from system environment

```
set:
  shield-env: true

targets:
  hello:
    script: |
      echo "Hello ${SOME_VAR}!"
```
`SOME_VAR=world tea hello`
result: `Hello !
