### ISSUE TITLE
Implement functionality to single-exec dependecies

### ISSUE THREAD

**Issue by kassybas** [kassybas/tea#7]
- Add opt to configure dependency to only execute if was not executed before
- Arguments are ignored in deciding to skip execution
Example
```
targets:
  release:
    deps:
      - build
      - test
      - deploy

  test:
    deps:
      - build: {}
         opts: once
      - unit-test
...
```
In this example `test` target only calls the build target, if it was not executed before (ie. not when test is called).
